[package]
name = "fluentai-lsp"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fluentai-core = { path = "../fluentai-core" }
fluentai-parser = { path = "../fluentai-parser" }
fluentai-vm = { path = "../fluentai-vm" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tower-lsp.workspace = true
tokio.workspace = true
ropey.workspace = true
tracing.workspace = true
dashmap = "5.5"
tracing-subscriber = "0.3"
once_cell = "1.19"

[[bin]]
name = "fluentai-lsp"
path = "src/main.rs"