[package]
name = "fluentai-bytecode"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fluentai-core = { path = "../fluentai-core" }
anyhow.workspace = true
serde.workspace = true