[package]
name = "fluentai-interpreter"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Core dependencies
fluentai-core = { path = "../fluentai-core" }
fluentai-stdlib = { path = "../fluentai-stdlib" }
fluentai-types = { path = "../fluentai-types" }
fluentai-effects = { path = "../fluentai-effects" }
fluentai-modules = { path = "../fluentai-modules" }
fluentai-contracts = { path = "../fluentai-contracts" }

# Data structures
rustc-hash = "2.0"
indexmap = "2.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Utilities
tracing = "0.1"
once_cell = "1.19"

# Async support
tokio = { version = "1.35", features = ["rt", "macros", "sync", "time"] }
async-trait = { version = "0.1" }

[dev-dependencies]
fluentai-parser = { path = "../fluentai-parser" }
proptest = "1.4"
criterion = "0.5"

[features]
default = []
debug = []
jit = []

[[bench]]
name = "interpreter_bench"
harness = false
