[package]
name = "fluentai-runtime"
version = "0.1.0"
edition = "2021"
authors = ["FluentAI Team"]
description = "Embedded runtime for FluentAI language"
license = "MIT"

[dependencies]
fluentai-core = { path = "../fluentai-core" }
fluentai-vm = { path = "../fluentai-vm" }
fluentai-parser = { path = "../fluentai-parser" }
fluentai-optimizer = { path = "../fluentai-optimizer" }
fluentai-stdlib = { path = "../fluentai-stdlib" }
fluentai-contracts = { path = "../fluentai-contracts" }
fluentai-effects = { path = "../fluentai-effects" }
fluentai-jit = { path = "../fluentai-jit", optional = true }

anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
parking_lot = "0.12"
dashmap = "5.5"
once_cell = "1.19"

[features]
default = ["jit"]
jit = ["fluentai-jit"]

[dev-dependencies]
criterion = "0.5"
tempfile = "3.8"