[package]
name = "fluentai-lint"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fluentai-core = { path = "../fluentai-core" }
fluentai-parser = { path = "../fluentai-parser" }
fluentai-types = { path = "../fluentai-types" }

# Core dependencies
anyhow = { workspace = true }
thiserror = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Pattern matching
regex = "1.10"
glob = "0.3"

# Diagnostics
miette = { version = "7.0", features = ["fancy"] }
ariadne = "0.4"

# Configuration
toml = "0.8"

# File walking
walkdir = "2.4"

# Lazy static
once_cell = "1.19"

[dev-dependencies]
pretty_assertions = "1.4"
