[package]
name = "fluentai-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
fluentai-core = { path = "../fluentai-core" }
fluentai-parser = { path = "../fluentai-parser" }
fluentai-vm = { path = "../fluentai-vm" }
fluentai-stdlib = { path = "../fluentai-stdlib" }

# MCP and async runtime
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Web framework
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }

# SSE and streaming
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
async-stream = "0.3"

# Session and state management
uuid = { version = "1.6", features = ["v4", "serde"] }
dashmap = "5.5"

# CLI
clap = { version = "4.4", features = ["derive"] }

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

[lib]
name = "fluentai_mcp"
path = "src/lib.rs"

[[bin]]
name = "fluentai-mcp"
path = "src/main.rs"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }